### ISSUE TITLE
List of issues to implement `rust → lambda`

### ISSUE THREAD

**Issue by InnocentusLime** [InnocentusLime/TRust#5]
List:
- [ ] Add syntax for types with fields
- [ ] Add `let` syntax
- [ ] Revisit rust grammar
- [ ] Function ordering

**Comment by InnocentusLime** [comment]
Closing due to irrelevancy
